name: ci
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - develop
      - develop-v5
permissions:
  contents: read
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ci:
    name: ci
    uses: studioespresso/.github/.github/workflows/ci.yml@main
    with:
      php_version: "8.4"
      craft_version: '5'
      jobs: '["ecs", "phpstan", "changelog"]'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
      - run: composer install --no-interaction --prefer-dist
      - run: vendor/bin/phpunit
